image: kroniak/ssh-client

variables:
  DEPLOY_SSH_USER: your.ssh.username
  DEPLOY_SSH_PORT: 22
  DEPLOY_SSH_HOST: your.ssh.server
  DEPLOY_SSH_PRIVATE_KEY: your.ssh.private.key
  WORK_DIR: /tmp

before_script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo "$DEPLOY_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa

stages:
  - deploy

do_something:
  stage: deploy
  script:
    - scp -v -P $DEPLOY_SSH_PORT something $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST:/${WORK_DIR}/
    - |
      ssh -p $DEPLOY_SSH_PORT -l $DEPLOY_SSH_USER $DEPLOY_SSH_HOST <<-EOF
        echo ${CI_COMMIT_SHA}
        cd ${WORK_DIR}
        pwd
        ls -lha
      EOF
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual
  allow_failure: false
