image: docker:19.03.12

services:
  - name: docker:19.03.12-dind
    alias: docker
    command: ["--mtu=1440"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: $CI_PROJECT_NAME
  IMAGE_TAG: $CI_COMMIT_SHA
  GROUP_NAME: your.registry.group
  REGISTRY_URL: your.registry.server
  REGISTRY_USER: your.registry.username
  REGISTRY_PASSWORD: your.registry.password

stages:
  - build
  - deploy

before_script:
  - docker info

build_image:
  stage: build
  variables:
    HTTP_PROXY: "http://your.squid.proxy:3128"
    HTTPS_PROXY: "http://your.squid.proxy:3128"
    NO_PROXY: "docker,localhost,127.0.0.1,.internal.domain"
  script:
    - export IMAGE=${REGISTRY_URL}/${GROUP_NAME}/${IMAGE_NAME}:${IMAGE_TAG}
    - docker build -t ${IMAGE} .

push_image:
  stage: deploy
  script:
    - export IMAGE=${REGISTRY_URL}/${GROUP_NAME}/${IMAGE_NAME}:${IMAGE_TAG}
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD} ${REGISTRY_URL}
    - docker push ${IMAGE}
